### ISSUE TITLE
Creating a composite with step when slicing a primitive with step>1

### ISSUE THREAD

**Issue by hakonsbm** [compneuronmbu/nest-simulator#16]
Until c7ca105c68ea0d6c7972ae1e80271b6d4447738a, when slicing a primitive GIDCollection with a step greater than one, a composite was created, containing single GID primitives, e.g.:
```
> /iaf_psc_alpha 10 Create [2 8 3] Take ==
[[size=3:
  [[model=iaf_psc_alpha, size=1 (2)]]
  [[model=iaf_psc_alpha, size=1 (5)]]
  [[model=iaf_psc_alpha, size=1 (8)]]]]
```
@stinebuu and I thought it would be cleaner and more efficient to instead convert it to a composite with built-in stepping, like we do when slicing a composite with a step greater than one. However this presents a problem when concatenating, as concatenating a composite with step>1 with another GIDCollection is currently not possible.

When joining two GIDCollections there are no other restrictions than preserving uniqueness of GIDs. So even in cases where the lowest GID of one GIDCollection is lower than the highest of the other, joining should be possible, provided that all GIDs are unique. The problem is with how stepping is represented in composites. Basically they keep all the GIDs, and skip a given number of GIDs each step. This skipping makes them incompatible with all other GIDCollections, however.

Therefore, we must decide if we should try to find a way to join composites that have a step greater than one, and if we don't, if we still want to keep using the built-in composite stepping when slicing primitives with step>1, or revert it back to the way it was.

**Comment by stinebuu** [comment]
Another restriction for adding two composites would be the metadata.

We want to do something like the following, right? That is where the problem arises?
```
n1 = nest.Create('iaf_psc_alpha', 10)
n2 = nest.Create('iaf_psc_delta', 5)
n3 = n1[::3] + n2
```

It's a long time since I've looked at this, but why is it that we do not have a step variable for the primitives? Then your example would turn into a primitive with a step, and I guess when we are working with the composites, we would need to check the primitive's step as well, which might get complicated. But we could have a rule about not slicing a composite with a sliced primitive, and I guess keep the rule about adding composites with a step (since we don't want to mix the steps of the primitives in the composite and the general step for the composite).

**Comment by hakonsbm** [comment]
I think we defined primitives to always be contiguous. But if we were to add an exception for primitives with a step, your example could work. However, if the GIDCollections overlap it becomes more difficult. Take for example
```python
n1 = nest.Create('iaf_psc_alpha', 10)
n1_a = n1[::3]   # [1, 4, 7, 10] 
n1_b = n1[1::3]  # [2, 5, 8]
n2 = n1_a + n1_b
```
The GIDs of `n1_b` would then have to go between the ones in `n1_a`.

One way joining GIDCollections involving stepping could work would be by assembling a new GIDCollection from the ones with step, essentially converting GIDCollections with step to the form in my first example before joining.

**Comment by stinebuu** [comment]
Did not think of that example! Your way sounds simpler :+1:

**Comment by hakonsbm** [comment]
I did some benchmarks iterating through composites resulting from slicing a primitive with step in the old and new way.

The first configuration (split) iterates through a composite split into single GID primitives, as one would get previously when slicing a primitive with step. The second configuration (step) iterates through a single primitive, but with step, as one gets now when slicing a primitive with step. In both cases the steplength is 2, and each is iterated 100 times. All times are given in seconds.

| neurons | split (old) | step (new) | speedup |
|---------|-------------|------------|---------|
| 1000    |      0.0523 |     0.0094 |     5.5 |
| 5000    |      1.2601 |     0.0372 |    33.8 |
| 10000   |      5.2397 |     0.0723 |    72.5 |
| 20000   |     21.5830 |     0.1320 |   163.5 |

**Comment by heplesser** [comment]
@hakonsbm Interesting work! Clearly, your benchmarks suggest that stepping primitives is the way to go. But I wonder if we are not making life too complicated for us. For what are actual use cases? Users will create populations of neurons once, and then may select neurons by slicing for connecting, e.g., devices, or modifying parameters. But I do not really see that all kinds of complex combinations of slices would be relevant in practice, so before creating very complex rules and code to support them, I would tend to simply not support certain complicated cases such as overlapping stepped slices.

**Comment by hakonsbm** [comment]
@heplesser I think it makes sense not to make things too complicated if there are no relevant use cases in practice. Should we just keep it the way it is now then, where slicing a GIDCollection with step makes it unable to be joined with any other GIDCollections?

**Comment by heplesser** [comment]
Yes, I'd suggest to not support joining slices.
