### ISSUE TITLE
Reminder: Possible duplicates of the output serialization to json

### ISSUE THREAD

**Issue by babsey** [compneuronmbu/nest-simulator#18]
This issue adress @stinebuu comment in https://github.com/nest/nest-simulator/pull/1123 that we might have duplicates of the function to serialize the output in `GetStatus` and `GetDefaults` functions (in NEST 2.x) as well as `GIDCollection` and `Connectome` objects (in NEST 3).  See pulled request #7.

**Comment by stinebuu** [comment]
Fixed by #20
