### ISSUE TITLE
Problem converting GIDCollection to numpy array on Travis

### ISSUE THREAD

**Issue by stinebuu** [compneuronmbu/nest-simulator#6]
We have set up Travis for the compneuronmbu nest-simulator repository! As you can see, there is currently only one test failing on Travis, namely `One-to-one connectivity using CGConnect with id intvectors` from test_csa.py. The problem is that it does not fail on my computer, even though I compile with `libneurosim` and have CSA. The other CSA tests also pass on my computer, so I don't think there is a problem with my installation of CSA or something like that.

Travis gives the following error message:
```
NESTError: unknown Python type: <type 'numpy.ndarray'>
```

This errormessage might come from pynestkernel when we push down to SLI, but I am not sure. I think I have gotten that kind of problem there before.

I also had problems with some other tests where Travis was not able to convert `GIDCollection` to `numpy.asarray(gid_collection)`, so I think we have the same problem with the csa test, with the [line:](https://github.com/compneuronmbu/nest-simulator/blob/fix-481-SubnetFreeTopology/pynest/nest/tests/test_csa.py#L102)
```
nest.CGConnect(numpy.array(sources), numpy.array(targets), cg)
```
I was able to fix those tests with `enumeration`, as we were to find the index of the GIDs in those test, but that obviously wont work here.

I am not sure why the test fails on Travis and not on my computer, and I also don't know how best to fix this. The point of the test is to use IntVectors, which we get from the numpy array. Converting the `GIDCollection` to a python list before passing it to the numpy array seems to me a bad solution, but it is the only one I can think of right now, so I hope you have some better solutions! And ideally, that somebody have some good ideas as to why we are not able to convert `GIDCollection` to `numpy.array` and `numpy.asarray` on travis, which I feel like we should be able to do.

**Comment by heplesser** [comment]
I think the is thrown by this code in pynestkernel.pyx:
```
        # NumPy < 1.5.0 doesn't support PEP-3118 buffer interface
        #
        if ret is NULL and HAVE_NUMPY and isinstance(obj, numpy.ndarray) and obj.ndim == 1:
            if numpy.issubdtype(obj.dtype, numpy.integer):
                ret = python_buffer_to_datum[object, long](obj)
            elif numpy.issubdtype(obj.dtype, numpy.floating):
                ret = python_buffer_to_datum[object, double](obj)
            else:
                raise NESTError("only vectors of integers or floats are supported")

        if ret is not NULL:
            return ret
        else:
            raise NESTError("unknown Python type: {0}".format(type(obj)))
```
Note the comment about NumPy 1.5.0---and do we have NumPy in our Travis setup? We may need to install it explicitly in the travis.yml file.

**Comment by stinebuu** [comment]
@heplesser yes, we do have NumPy in our Travis setup, we do a `sudo apt-get install python-numpy` in line 69, so this shouldn't be the problem.

It does indeed seem like the code snippet you posted is where the error is thrown. I still don't understand why it does not happen on my local computer, but I will try to investigate some more. The newest version of NumPy is 1.14.3, which is the one Travis should install, but I don't know enough about Travis, maybe it does not have the newest versions?

**Comment by heplesser** [comment]
@stinebuu Weird. 1.14 should definitely be new enough. Could you check with @lekshmideepu if she has any idea what may be going on and how one could debug this in a reasonably efficient way?

**Comment by stinebuu** [comment]
@heplesser The problem is solved with the new Travis setup in master. Once I remembered nest#789 I merged master into the subnetfree topology branch to see if it helped, and now everything pass.
