### ISSUE TITLE
Iterate Connectome

### ISSUE THREAD

**Issue by stinebuu** [compneuronmbu/nest-simulator#9]
It is currently not possible to iterate a `Connectome`, see [#2](https://github.com/compneuronmbu/nest-simulator/issues/2#issuecomment-348949697). The reasoning is that if you want to slice a `Connectome`, you should do so with `GetConnections()`. However, in a recent e-mail discussion with @babsey, it was mentioned that it might be nice to provide iteration if you want to set some parameters (`weight` and `delay`), and that this would be consistent with what is possible with `GIDCollection`.

I am a bit hesitant to allow iteration, because I don't always think it is obvious which connections are returned when we slice or iterate, and this might lead to mistakes. The order might change if we sort connections by source or not as well. It is quite easy to set parameters with the `set()` function, and iterate through the specs if you first call `get()`. However, I can be persuaded to see things differently, and I must admit that I might be colored by the fact that a lot of the tests used to iterate the connections and I worked quite a bit to convert that to fit with the current `Connectome` class.

**Comment by heplesser** [comment]
@stinebuu Good point that we do not make any guarantees on order of connections in the `Connectome`, and that this means we need to be a bit careful about iteration. But I think we should support it, including slicing. You should not need to call `GetConnections()` on a full connectome first and then slice the result.
